# Generated by Django 4.1.3 on 2022-11-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skilltype_skill_skill_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilltype',
            options={'verbose_name_plural': 'Skill Type'},
        ),
    ]
